FLASK_APP=app.py
FLASK_DEBUG=True
SECRET_KEY=MustBeChaged

MAIL_SERVER=127.0.0.1
MAIL_PORT=1025
MAIL_USE_TLS=
MAIL_USERNAME=
MAIL_PASSWORD=

APP_NAME="Abzarha"
ADMINS="safari.tafreshi@gmail.com,sara.safari@gmail.com"
PER_PAGE=10