"""empty message

Revision ID: 175bae1edd9b
Revises: f4b5a9ef0667
Create Date: 2025-01-23 21:09:35.638989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175bae1edd9b'
down_revision = 'f4b5a9ef0667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('file', schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f('ix_file_note_id'))
    #    batch_op.drop_index(batch_op.f('ix_file_post_id'))
    #    batch_op.drop_index(batch_op.f('ix_file_user_id'))


    op.drop_table('file')
    # ### end Alembic commands ###
