"""empty message

Revision ID: 4ec8f8709e4b
Revises: 5e3a3051aa0b
Create Date: 2025-01-17 20:19:08.465032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec8f8709e4b'
down_revision = '5e3a3051aa0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(length=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_note_lang'), ['lang'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_lang'))
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
