"""empty message

Revision ID: 555e94ef0fea
Revises: b1a83b55cf34
Create Date: 2025-01-27 21:46:00.753245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555e94ef0fea'
down_revision = 'b1a83b55cf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('file_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('file_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('file_ibfk_2', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('file_ibfk_1', 'note', ['note_id'], ['id'])

    # ### end Alembic commands ###
