"""empty message

Revision ID: 744cf415cacc
Revises: e2ddb5de9806
Create Date: 2024-12-26 21:42:47.482387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744cf415cacc'
down_revision = 'e2ddb5de9806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    # ### end Alembic commands ###
