"""word table

Revision ID: a37dd361ed8f
Revises: cdac2fdaec12
Create Date: 2025-01-04 10:38:03.493233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37dd361ed8f'
down_revision = 'cdac2fdaec12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['dict_lang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_lang_id'), ['lang_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_lang_id'))

    op.drop_table('word')
    # ### end Alembic commands ###
